name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: "2"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        test-collection:
          - Categories
          - Subcategories
          - Pagination
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Start backend
      run: nohup node backend/index.js &
    - name: Wait for backend to be available
      run: npx wait-on tcp:4000
    - name: Run tests
      run: npx newman run postman-collections/${{ matrix.test-collection }}.postman_collection.json
