name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  endpoint-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    # Step to run the backend before running each Postman collection
    - name: Run backend and test Category-levels collection
      run: |
        if lsof -i :4000; then
          lsof -ti :4000 | xargs kill -9
        fi
        nohup node backend/index.js &
        sleep 10 
        npx newman run postman-collections/Categories.postman_collection.json

    - name: Run backend and test Subcategories collection
      run: |
        if lsof -i :4000; then
          lsof -ti :4000 | xargs kill -9
        fi
        nohup node backend/index.js &
        sleep 10
        npx newman run postman-collections/Subcategories.postman_collection.json

    - name: Run backend and test Pagination collection
      run: |
        if lsof -i :4000; then
          lsof -ti :4000 | xargs kill -9
        fi
        nohup node backend/index.js &
        sleep 10
        npx newman run postman-collections/Pagination.postman_collection.json

    - name: Run backend and test Product Data Validation collection
      run: |
        if lsof -i :4000; then
          lsof -ti :4000 | xargs kill -9
        fi
        nohup node backend/index.js &
        sleep 10 
        npx newman run postman-collections/Product_Data_Validation.postman_collection.json

    - name: Run backend and test Sorting collection
      run: |
        if lsof -i :4000; then
          lsof -ti :4000 | xargs kill -9
        fi
        nohup node backend/index.js &
        sleep 10
        npx newman run postman-collections/Sorting.postman_collection.json

    # - name: Run backend and test Third-level-categories collection
    #   run: |
    #     if lsof -i :4000; then
    #       lsof -ti :4000 | xargs kill -9
    #     fi
    #     nohup node backend/index.js &
    #     sleep 10
    #     npx newman run postman-collections/Third_level_categories.postman_collection.json
