name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  endpoint-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    # Step to run the backend before running each Postman collection
    - name: Run backend and test Category-levels collection
      run: |
        nohup node backend/index.js &
        sleep 10 
        npx newman run postman-collections/Category-levels.postman_collection.json

    - name: Run backend and test Subcategories collection
      run: |
        nohup node backend/index.js &
        sleep 10
        npx newman run postman-collections/Subcategories.postman_collection.json

    - name: Run backend and test Third-level-categories collection
      run: |
        nohup node backend/index.js &
        sleep 10
        npx newman run postman-collections/Third_level_categories.postman_collection.json
