name: Node.js CI

on:
  push:
    branches: [endpoint-testning-cucumber-chai-fetch]
  pull_request:
    branches: [endpoint-testning-cucumber-chai-fetch]

# jobs to run
jobs:
  # build, the name of the job, a server to create and auto configure
  endpoint-tests:

    runs-on: ubuntu-latest

    strategy:
      # only testing on Node 18 now but could have done
      # several builds by adding [16.x, 18.x] etc
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
     
    - run: npm ci
     
    - run: nohup node backend/index.js &
    
    - run: npm test
