name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  endpoint-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Install Newman and htmlextra Reporter
        run: |
          npm install -g newman@latest
          npm install -g newman-reporter-htmlextra

      - name: Check Postman Collection Exists
        run: |
          if [ ! -f postman-collections/mataffaren.collection.json ]; then
            echo "Postman collection file not found!"
            exit 1
          fi

      - name: Run Newman Tests and Export Results
        run: |
          newman run postman-collections/mataffaren.collection.json \
            --reporters htmlextra \
            --reporter-htmlextra-export test_results.html \
            --suppress-exit-code \
            --verbose

      - name: Upload Test Results to Discord
        if: always()
        env:
          DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/1226464109680263219/cfAUULyxtqG79ydcUXW_5oeZKcFu6E7PeFiik8-b3R_GFjLVlnJOcU9Y8rClh0jgl5po
        run: |
          if [ -f test_results.html ]; then
            curl -X POST -H 'Content-Type: multipart/form-data' \
              -F "file=@test_results.html" \
              -F "payload_json={\"content\":\"Test results file:\"}" \
              $DISCORD_WEBHOOK_URL
          fi

      - name: Send Discord Notification Test Passed
        if: always()
        env:
          DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/1226464109680263219/cfAUULyxtqG79ydcUXW_5oeZKcFu6E7PeFiik8-b3R_GFjLVlnJOcU9Y8rClh0jgl5po
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"content":"Postman tests are completed!"}' \
            $DISCORD_WEBHOOK_URL
